import {Flags} from './Flags';
const countryInfo={
    tl:{
        name:"East Timor",
        capital:"Dili",
        population:1066409,
        area:14874,
        flag:Flags.tl
    },
    ca:{
        name:"Canada",
        capital:"Otawa",
        population:35295770,
        area:9970610,
        flag:Flags.ca
    },
    tm:{
        name:"Turkmenistan",
        capital:"Ashgabat",
        population:5240000,
        area:488100,
        flag:Flags.tm
    },
    us:{
        name:"United States",
        capital:"Washington",
        population:317706000,
        area:9629090,
        flag:Flags.us
    },
    kh:{
        name:"Cambodia",
        capital:"Phnom Penh",
        population:15135000,
        area:181035,
        flag:Flags.kh
    },
    et:{
        name:"Ethiopia",
        capital:"Addis Ababa",
        population:86613986,
        area:1104300,
        flag:Flags.et
        
    },
    sz:{
        name:"Swaziland",
        capital:"Mbabane",
        population:1250000,
        area:17364,
        flag:Flags.sz
    },
    ar:{
        name:"Argentina",
        capital:"Buenos Aires",
        population:41660096,
        area:2780400,
        flag:Flags.ar
    },
    bo:{
        name:"Bolivia",
        capital:"Sucre",
        population:10027254,
        area:1098580,
        flag:Flags.bo
    },
    cm:{
        name:"Cameroon",
        capital:"Yaoundé",
        population:20386799,
        area:475442,
        flag:Flags.cm
    },
    bf:{
        name:"Burkina Faso",
        capital:"Ouagadougou",
        population:17322796,
        area:274000,
        flag:Flags.bf
    },
    gh:{
        name:"Ghana",
        capital:"Accra",
        population:24658000,
        area:238553,
        flag:Flags.gh
    },
    sa:{
        name:"Saudi Arabia",
        capital:"Riyadh",
        population:29994272,
        area:2149690,
        flag:Flags.sa
    },
    si:{
        name:"Slovenia",
        capital:"Ljubljana",
        population:2061963,
        area:20.256,
        flag:Flags.si
    },
    gt:{
        name:"Guatemala",
        capital:"Guatemala City",
        population:15806675,
        area:108889,
        flag:Flags.gt
    },
    ba:{
        name:"Bosnia and Herzegovina",
        capital:"Sarajevo",
        population:3791622,
        area:51197,
        flag:Flags.ba
    },
    kw:{
        name:"Kuwait",
        capital:"Kuwait City",
        population:3065850,
        area:17.818,
        flag:Flags.kw
    },
    ru:{
        name:"Russia Federation",
        capital:"Moscow",
        population:143700000,
        area:17098.200,
        flag:Flags.ru
    },
    jo:{
        name:"Jordan",
        capital:"Amman",
        population:6558900,
        area:89.342,
        flag:Flags.jo
    },
    lc:{
        name:"St. Lucia",
        capital:"Castries",
        population:180000,
        area:539,
        flag:Flags.lc
    },
    es:{
        name:"Spain",
        capital:"Madrid",
        population:46609700,
        area:505992,
        flag:Flags.es
    },
    lr:{
        name:"Liberia",
        capital:"Monrovia",
        population:4294000,
        area:111369,
        flag:Flags.lr
    },
    nl:{
        name:"Netherlands",
        capital:"Amsterdam",
        population:16842200,
        area:41.528,
        flag:Flags.nl
    },
    py:{
        name:"Paraguay",
        capital:"Asunción",
        population:6783374,
        area:406752,
        flag:Flags.py
    },
    om:{
        name:"Oman",
        capital:"Muscat",
        population:3957000,
        area:309500,
        flag:Flags.om
    },
    tz:{
        name:"Tanzania",
        capital:"Dodoma",
        population:44928923,
        area:945087,
        flag:Flags.tz
    },
    ga:{
        name:"Gabon",
        capital:"Libreville",
        population:1672000,
        area:267668,
        flag:Flags.ga
        
    },
    mc:{
        name:"Monaco",
        capital:"Monaco",
        population:36136,
        area:2,
        flag:Flags.mc
    },
    ye:{
        name:"Yemen",
        capital:"Sanaá",
        population:25235000,
        area:527968,
        flag:Flags.ye
    },
    pk:{
        name:"Pakistan",
        capital:"Islamabad",
        population:185914000,
        area:796095,
        flag:Flags.pk
    },
    al:{
        name:"Albania",
        capital:"Tirana",
        population:2821977,
        area:29748,
        flag:Flags.al
    },
    ae:{
        name:"United Arab Emirates",
        capital:"Abu Dhabi",
        population:8264070,
        area:83.600,
        flag:Flags.ae
    },
    in:{
        name:"India",
        capital:"New Delhi",
        population:1241610000,
        area:3287260,
        flag:Flags.ind
    },
    az:{
        name:"Azerbaijan",
        capital:"Baku",
        population:9477100,
        area:86600,
        flag:Flags.az
    },
    ls:{
        name:"Lesotho",
        capital:"Maseru",
        population:2074000,
        area:30.355,
        flag:Flags.ls
    },
    ke:{
        name:"Kenya",
        capital:"Nairobi",
        population:44354000,
        area:580.367,
        flag:Flags.ke
    },
    kr:{
        name:"South Korea",
        capital:"Seoul",
        population:50219669,
        area:99.538 ,
        flag:Flags.kr
    },
    tj:{
        name:"Tajikistan",
        capital:"Dushanbe",
        population:8160000,
        area:143.100,
        flag:Flags.tj
    },
    tr:{
        name:"Turkey",
        capital:"Ankara",
        population:76667864,
        area:783.562,
        flag:Flags.tr
    },
    af:{
        name:"Afghanistan",
        capital:"Kabul",
        population:25500100,
        area:652090,
        flag:Flags.af
    },
    bd:{
        name:"Bangladesh",
        capital:"Dhaka",
        population:152518015,
        area:143998,
        flag:Flags.bd
    },
    mr:{
        name:"Mauritania",
        capital:"Nouakchott",
        population:3461041,
        area:1025520,
        flag:Flags.mr
    },
    sb:{
        name:"Solomon Islands",
        capital:"Honiara",
        population:581344,
        area:28.896,
        flag:Flags.sb
    },
    sm:{
        name:"San Marino",
        capital:"San Marino",
        population:33.540,
        area:61,
        flag:Flags.sm
    },
    kg:{
        name:"Kyrgyzstan",
        capital:"Bishkek",
        population:5663133,
        area:199.900,
        flag:Flags.kg
    },
    mn:{
        name:"Mongolia",
        capital:"Ulaanbaatar",
        population:2931300,
        area:1564120,
        flag:Flags.mn
    },
    fr:{
        name:"France",
        capital:"Paris",
        population:65844000,
        area:551500,
        flag:Flags.fr
    },
    rw:{
        name:"Rwanda",
        capital:"Kigali",
        population:10537222,
        area:26.338,
        flag:Flags.rw
    },
    sk:{
        name:"Slovakia",
        capital:"Bratislava",
        population:5415949,
        area:49.033,
        flag:Flags.sk
    },
    so:{
        name:"Somalia",
        capital:"Mogadishu",
        population:10496000,
        area:637657,
        flag:Flags.so
    },
    pe:{
        name:"Peru",
        capital:"Lima",
        population:30475144,
        area:1285220,
        flag:Flags.pe
    },
    la:{
        name:"Laos",
        capital:"Vientiane",
        population:6580800,
        area:236.800,
        flag:Flags.la
    },
    no:{
        name:"Norway",
        capital:"Oslo",
        population:5109056,
        area:385.155,
        flag:Flags.no
    },
    mw:{
        name:"Malawi",
        capital:"Lilongwe",
        population:16363000,
        area:118.484,
        flag:Flags.mw
    },
    bj:{
        name:"Benin",
        capital:"Porto-Novo",
        population:10323000,
        area:112622,
        flag:Flags.bj
    },
    sg:{
        name:"Singapore",
        capital:"Singapore",
        population:5399200,
        area:683,
        flag:Flags.sg
    },
    me:{
        name:"Montenegro",
        capital:"Podgorica",
        population:620029,
        area:13.812,
        flag:Flags.me
    },
    tg:{
        name:"Togo",
        capital:"Lomé",
        population:6191155,
        area:156.785,
        flag:Flags.tg
    },
    cn:{
        name:"China",
        capital:"Beijing",
        population:1363350000,
        area:9640820,
        flag:Flags.cn
    },
    am:{
        name:"Armenia",
        capital:"Yerevan",
        population:3017400,
        area:29800,
        flag:Flags.am
    },
    do:{
        name:"Dominican Republic",
        capital:"Santo Domingo",
        population:9445281,
        area:48671,
        flag:Flags.domrep
    },
    ua:{
        name:"Ukraine",
        capital:"Kiev",
        population:45426200,
        area:603.700,
        flag:Flags.ua
    },
    bh:{
        name:"Bahrain",
        capital:"Manama",
        population:1234571,
        area:694,
        flag:Flags.bh
    },
    fi:{
        name:"Finland",
        capital:"Helsinki",
        population:5452821,
        area:338141,
        flag:Flags.fi
    },
    ly:{
        name:"Lybia",
        capital:"Tripoli",
        population:6202000,
        area:1759.540,
        flag:Flags.ly
    },
    id:{
        name:"Indonesia",
        capital:"Jakarta",
        population:249866000,
        area:1904570,
        flag:Flags.id
    },
    cf:{
        name:"Central African Republic",
        capital:"Bangui",
        population:4616000,
        area:622984,
        flag:Flags.cf
    },
    se:{
        name:"Sweden",
        capital:"Stockholm",
        population:9651531,
        area:449.964,
        flag:Flags.se
    },
    vn:{
        name:"Vietnam",
        capital:"Hanoi",
        population:89708900,
        area:331.689,
        flag:Flags.vn
    },
    ml:{
        name:"Mali",
        capital:"Bamako",
        population:15302000,
        area:1240190,
        flag:Flags.ml
    },
    bg:{
        name:"Bulgaria",
        capital:"Sofia",
        population:7282041,
        area:110912,
        flag:Flags.bg
    },
    ro:{
        name:"Romania",
        capital:"Bucharest",
        population:20121641,
        area:238.391,
        flag:Flags.ro
    },
    ao:{
        name:"Angola",
        capital:"Luanda",
        population:20609294,
        area:1246700,
        flag:Flags.ao
    },
    td:{
        name:"Chade",
        capital:"N'Djamena",
        population:12825000,
        area:1284000,
        flag:Flags.td
    },
    vc:{
        name:"St. Vincent and the Grenadines",
        capital:"Kingstown",
        population:109000,
        area:388,
        flag:Flags.vc
    },
    ni:{
        name:"Nicaragua",
        capital:"Managua",
        population:6071045,
        area:130000,
        flag:Flags.ni
    },
    li:{
        name:"Liechtenstein",
        capital:"Vaduz",
        population:37132,
        area:160,
        flag:Flags.li
    },
    ag:{
        name:"Antigua & Barbuda",
        capital:"St John's",
        population:86295,
        area:442,
        flag:Flags.ag
    },
    my:{
        name:"Malaysia",
        capital:"Kuala Lumpur",
        population:30041000,
        area:329.847,
        flag:Flags.my
    },
    sn:{
        name:"Senegal",
        capital:"Dakar",
        population:13567338,
        area:196.722,
        flag:Flags.sn
    },
    mz:{
        name:"Mozambique",
        capital:"Maputo",
        population:23700715,
        area:801.590,
        flag:Flags.mz
    },
    ug:{
        name:"Uganda",
        capital:"Kampala",
        population:35357000,
        area:241.038,
        flag:Flags.ug
    },
    jp:{
        name:"Japan",
        capital:"Tokyo",
        population:127180000,
        area:377.873,
        flag:Flags.jp
    },
    ne:{
        name:"Niger",
        capital:"Niamey",
        population:17129076,
        area:1267000,
        flag:Flags.ne
    },
    br:{
        name:"Brazil",
        capital:"Brasilia",
        population:201032714,
        area:8514880,
        flag:Flags.br
    },
    gn:{
        name:"Guinea",
        capital:"Conakry",
        population:10824000,
        area:245857,
        flag:Flags.gn
    },
    pa:{
        name:"Panama",
        capital:"Panama City",
        population:3405813,
        area:75517,
        flag:Flags.pa
    },
    gy:{
        name:"Guyana",
        capital:"Georgetown",
        population:784984,
        area:214969,
        flag:Flags.gy
    },
    cr:{
        name:"Costa Rica",
        capital:"San José",
        population:4667096,
        area:51.100,
        flag:Flags.cr
    },
    lu:{
        name:"Luxembourg",
        capital:"Luxembourg City",
        population:537.000,
        area:2.586,
        flag:Flags.lu
    },
    ad:{
        name:"Andorra",
        capital:"Andorra la Vella",
        population:76098,
        area:468,
        flag:Flags.ad
    },
    ci:{
        name:"Ivory Coast",
        capital:"Yamoussoukro",
        population:23202000,
        area:322463,
        flag:Flags.ci
    },
    sy:{
        name:"Syria",
        capital:"Damascus",
        population:21898000,
        area:185180,
        flag:Flags.sy
    },
    ng:{
        name:"Nigeria",
        capital:"Abuj",
        population:173615000,
        area:923768,
        flag:Flags.ci
    },
    eq:{
        name:"Equador",
        capital:"Quito",
        population:15699200,
        area:283561,
        flag:Flags.eq
    },
    cz:{
        name:"Czech Republic",
        capital:"Prague",
        population:10513800,
        area:78866,
        flag:Flags.cz
    },
    bn:{
        name:"Brunei",
        capital:"Bandar Seri Begawan",
        population:393162,
        area:5765000,
        flag:Flags.bn
    },
    au:{
        name:"Australia",
        capital:"Canberra",
        population:23414552,
        area:7741229,
        flag:Flags.au
    },
    ir:{
        name:"Iran",
        capital:"Tehran",
        population:77288000,
        area:1648200,
        flag:Flags.ir
    },
    dz:{
        name:"Algeria",
        capital:"Algiers",
        population:38700000,
        area:2381748,
        flag:Flags.dz
    },
    sv:{
        name:"El Salvador",
        capital:"San Salvador",
        population:6340000,
        area:21041,
        flag:Flags.sv
    },
    kn:{
        name:"St. Kitts and Nevis",
        capital:"Basseterre",
        population:54000,
        area:261,
        flag:Flags.kn
    },
    cl:{
        name:"Chile",
        capital:"Santiago",
        population:16341929,
        area:756096,
        flag:Flags.cl
    },
    be:{
        name:"Belgium",
        capital:"Brussels",
        population:11132269,
        area:32545,
        flag:Flags.be
    },
    th:{
        name:"Thailand",
        capital:"Bangkok",
        population:65926261,
        area:513115,
        flag:Flags.th
    },
    ht:{
        name:"Haiti",
        capital:"Port-au-Prince",
        population:10413211,
        area:27750,
        flag:Flags.ht
    },
    iq:{
        name:"Iraq",
        capital:"Baghdad",
        population:34035000,
        area:438.317,
        flag:Flags.iq
    },
    sl:{
        name:"Sierra Leone",
        capital:"Freetown",
        population:6190280,
        area:71.740,
        flag:Flags.sl
    },
    ge:{
        name:"Georgia",
        capital:"Tbillisi",
        population:4483800,
        area:69700,
        flag:Flags.ge
    },
    gm:{
        name:"Gambia",
        capital:"Banjul",
        population:1849000,
        area:11295,
        flag:Flags.gm
    },
    ph:{
        name:"Philippines",
        capital:"Manila",
        population:99275100,
        area:300000,
        flag:Flags.ph
    },
    md:{
        name:"Moldova",
        capital:"Chisinau",
        population:3559500,
        area:33.851,
        flag:Flags.md
    },
    ma:{
        name:"Morocco",
        capital:"Rabbat",
        population:33202300,
        area:446550,
        flag:Flags.ma
    },
    na:{
        name:"Namibia",
        capital:"Windhoek",
        population:2113077,
        area:824292,
        flag:Flags.na
    },
    gw:{
        name:"Guinea-Bissau",
        capital:"Bissau",
        population:1704000,
        area:36125,
        flag:Flags.gw
    },
    ch:{
        name:"Switzerland",
        capital:"Bern",
        population:8112200,
        area:41.284,
        flag:Flags.ch
    },
    gd:{
        name:"Grenada",
        capital:"St George",
        population:103328,
        area:344,
        flag:Flags.gd

    },
    bz:{
        name:"Belize",
        capital:"Belmopan",
        population:349728,
        area:22966,
        flag:Flags.bz
    },
    pt:{
        name:"Portugal",
        capital:"Lisbon",
        population:10487289,
        area:91982,
        flag:Flags.pt
    },
    ee:{
        name:"Estonia",
        capital:"Tallinn",
        population:1311870,
        area:45100,
        flag:Flags.ee
    },
    uy:{
        name:"Uruguay",
        capital:"Montevideo",
        population:3286314,
        area:175.016,
        flag:Flags.uy
    },
    gq:{
        name:"Equatorial Guinea",
        capital:"Malabo",
        population:736296,
        area:28051,
        flag:Flags.gq
    },
    lb:{
        name:"Lebannon",
        capital:"Beirut",
        population:4822000,
        area:10.400,
        flag:Flags.lb
    },
    uz:{
        name:"Uzbekistan",
        capital:"Tashkent",
        population:30183400,
        area:447.400,
        flag:Flags.uz
    },
    eg:{
        name:"Egypt",
        capital:"Cairo",
        population:86127000,
        area:980869,
        flag:Flags.eg
    },
    dj:{
        name:"Djibouti",
        capital:"Djibouti",
        population:873000,
        area:23200,
        flag:Flags.dj
    },
    co:{
        name:"Colombia",
        capital:"Bogotá",
        population:47506000,
        area:1138910,
        flag:Flags.co
    },
    bi:{
        name:"Burundi",
        capital:"Bujumbura",
        population:10163000,
        area:27834,
        flag:Flags.bi
    },
    tw:{
        name:"Taiwan",
        capital:"Taipei",
        population:23379129,
        area:36.188,
        flag:Flags.tw
    },
    cy:{
        name:"Cyprus",
        capital:"Nicosia",
        population:865878,
        area:9251,
        flag:Flags.cy
    },
    qa:{
        name:"Qatar",
        capital:"Doha",
        population:2045239,
        area:11000,
        flag:Flags.qa
    },
    it:{
        name:"Italy",
        capital:"Rome",
        population:59943933,
        area:301.318,
        flag:Flags.it
    },
    bt:{
        name:"Bhutan",
        capital:"Thimphu",
        population:745000,
        area:47000,
        flag:Flags.bt
    },
    sd:{
        name:"Sudan",
        capital:"Khartoum",
        population:37964000,
        area:2505810,
        flag:Flags.sd
    },
    np:{
        name:"Nepal",
        capital:"Kathmandu",
        population:26494504,
        area:147181,
        flag:Flags.np
    },
    cd:{
        name:"Democratic Republic of the Congo",
        capital:"Kinshasa",
        population:267514000,
        area:2344860,
        flag:Flags.cd
    },
    sr:{
        name:"Suriname",
        capital:"Paramaribo",
        population:534189,
        area:163820,
        flag:Flags.sr
    },
    ve:{
        name:"Venezuela",
        capital:"Caracas",
        population:28946101,
        area:912050,
        flag:Flags.ve
    },
    il:{
        name:"Israel",
        capital:"Jerusalem",
        population:8146300,
        area:22.145,
        flag:Flags.il
    },
    zm:{
        name:"Zambia",
        capital:"Lusaka",
        population:14580290,
        area:752618,
        flag:Flags.zm
    },
    at:{
        name:"Austria",
        capital:"Vienna",
        population:8504850,
        area:83858,
        flag:Flags.at
    },
    pg:{
        name:"Papua New Guinea",
        capital:"Port Moresby",
        population:7398500,
        area:462840,
        flag:Flags.pg
    },
    zw:{
        name:"Zimbabwe",
        capital:"Harare",
        population:12973808,
        area:390757,
        flag:Flags.zw
    },
    de:{
        name:"Germany",
        capital:"Berlin",
        population:80619000,
        area:357022,
        flag:Flags.de
    },
    dk:{
        name:"Denmark",
        capital:"Copenhagen",
        population:5627235,
        area:43094,
        flag:Flags.dk
    },
    kz:{
        name:"Kazakhstan",
        capital:"Astana",
        population:17186000,
        area:2724.900,
        flag:Flags.kz
    },
    pl:{
        name:"Poland",
        capital:"Warsaw",
        population:38502396,
        area:312685,
        flag:Flags.pl
    },
    er:{
        name:"Eritrea",
        capital:"Asmara",
        population:6333000,
        area:117600,
        flag:Flags.er
    },
    ie:{
        name:"Ireland",
        capital:"Dublin",
        population:4593100,
        area:70.273,
        flag:Flags.ie
    },
    mk:{
        name:"Macedonia",
        capital:"Skopje",
        population:2062294,
        area:25.713,
        flag:Flags.ie
    },
    kp:{
        name:"North Korea",
        capital:"Pyongyang",
        population:24895000,
        area:120538,
        flag:Flags.kp
    },
    tt:{
        name:"Trinidad and Tobago",
        capital:"Port of Spain",
        population:1328019,
        area:5.130,
        flag:Flags.tt
    },
    lv:{
        name:"Latvia",
        capital:"Riga",
        population:2003900,
        area:64.600,
        flag:Flags.lv
    },
    hu:{
        name:"Hungary",
        capital:"Budapest",
        population:9906000,
        area:93032,
        flag:Flags.hu
    },
    by:{
        name:"Belarus",
        capital:"Minsk",
        population:9468100,
        area:207600,
        flag:Flags.by
    },
    hn:{
        name:"Honduras",
        capital:"Tegucigalpa",
        population:8555072,
        area:112088,
        flag:Flags.hn
    },
    mm:{
        name:"Myanmar",
        capital:"Naypyidaw",
        population:53259000,
        area:676578,
        flag:Flags.mm
    },
    mx:{
        name:"Mexico",
        capital:"Mexico City",
        population:119713203,
        area:1958200,
        flag:Flags.mx
    },
    tn:{
        name:"Tunisia",
        capital:"Tunis",
        population:10886500,
        area:163610,
        flag:Flags.tn
    },
    gb:{
        name:"United Kingdom",
        capital:"London",
        population:63705000,
        area:242900,
        flag:Flags.gb
    },
    cg:{
        name:"Congo",
        capital:"Brazzaville",
        population:4448000,
        area:342000,
        flag:Flags.cg
    },
    xk:{
        name:"Yugoslavia",
        capital:"Zagreb",
        population:4290612,
        area:56538,
        flat:Flags.hr

    },
    gr:{
        name:"Greece",
        capital:"Athens",
        population:10815197,
        area:131957,
        flag:Flags.gr
    },
    lk:{
        name:"Sri Lanka",
        capital:"Colombo",
        population:20277597,
        area:65.610,
        flag:Flags.lk
    },
    hr:{
        name:"Croatia",
        capital:"Zagreb",
        population:4290612,
        area:56538,
        flat:Flags.hr
    },
    bw:{
        name:"Botswana",
        capital:"Gaborone",
        population:2024904,
        area:581730,
        flag:Flags.bw
    },
    za:{
        name:"South Africa",
        capital:"Pretoria",
        population:52981991,
        area:1221040,
        flag:Flags.za
    }
};
const forcePreloader=[
    'Don´t worry about tests, Chuck Norris´s test cases cover your code too.',
    '21 December 2012 was to be the day the Mayans predicted somebody would tell Chuck Norris that he´s not so cool after all.',
    'Chuck Norris eats soup with a fork, KFC with chopsticks, and bananas with his feet.',
    'Chuck Norris once caught an eighty pound tuna while spearfishing in a mirage.',
    'Chuck Norris can literally kill time.',
    'Chuck Norris changed the law of BODMAS to ROUNDHOUSE',
    'It should go without saying Chuck Norris leaves a trail of vanquished supermodels in his wake wherever he goes.',
    'Chuck Norris hides in plain sight.',
    'A circus clown once bumped into Chuck Norris. It took him only three seconds to twist the clown into an animal balloon.',
    'A Chuck Norris fact a day keeps his roundhouse kicks away.',
    'One time, at band camp, Chuck Norris ate a percussionist.',
    'Chuck norris once gave his grandma a ball of steal wool and she knitted him a bmx.',
    'Chuck Norris ordered some sushi in a Chinese restaurant and got one.',
    'Chuck Norris can build a computer with Windows 7.',
    'Only God is allowed to edit Chuck Norris´s Wikipedia page.',
    'Chuck Norris was born December 32nd',
    'Chuck Norris can squeeze carviar out of a lemon.',
    'When life gives Chuck Norris lemons, he destroys an orphanage',
    'When Chuck Norris cuts onions, the onions cry!',
    'Chuck Norris irons his clothes by wearing them.',
    'Chuck Norris heartbeat was the cause of the 1906 earthquake',
    'Chuck Norris can deny the License Agreement and still be able to install the software',
    'Zeus from Greek myth fathered many children, has a beard, and killed his own father. No, Zeus is not Chuck Norris. Chuck Norris killed Zeus for copying him.',
    'Chuck Norris will roundhouse kick you to death if you laugh at Chuck Norris jokes. He will also roundhouse kick you to death if you don`t laugh at Chuck Norris jokes. The choice is yours.',
    'The only things you can be sure of are Chuck Norris and taxes.',
    'Chuck Norris dunks onion rings in his morning coffee.',
    'Chuck Norris knew where the stolen Death Star plans were.(and he also knew where that shuttle was going.)',
    'Einstein may have invented the therory of relativity- Chuck Norris invented the reality of kicking ass.',
    'When Chuck Norris wants an egg, he cracks open a chicken.',
    'Chuck Norris shaves with a belt sander',
    'Chuck Norris regularly performs mind tricks on Jedi Knights.',
    'Chuck Norris abducts aliens',
    'The Avatar was created by Chuck Norris uppercutting a smurf.',
    'Chuck Norris can play Angry Birds from a payphone.'
];
const svgDimensions={
    charts:{
        width:820,
        height:470,
    },
    margins:{
        top: 30,
        right: 20,
        bottom: 30,
        left: 30
    }
};
const Months=["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
export const dataVisConstant={forcePreloader,countryInfo,svgDimensions}